pub type Error {
  OutOfRange
}

pub fn say(number: Int) -> Result(String, Error) {
  todo
}
